FROM node:alpine as builder

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

FROM nginx

COPY --from=builder /app/dist /usr/share/nginx/html
COPY --from=builder /app/nginx.conf /etc/nginx/nginx.conf

## Copy the default nginx.conf provided by tiangolo/node-frontend
#COPY --from=build /app/nginx.conf /etc/nginx/conf.d/default.conf